version: '3.7'

services:
  mysql_db:
    container_name: 2ndgoods_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 2ndgoods
      MYSQL_ROOT_PASSWORD: longdeeptry123
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - 2ndgoods_net
  app_be:
    container_name: 2ndgoods_be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - sh
      - -c
      - 'npm start'
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    volumes:
      - be:/app
    networks:
      - 2ndgoods_net
    
networks:
  2ndgoods_net:
    driver: bridge

volumes:
  db:
  be: