version: '3.7'

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: 300618
  MYSQL_DATABASE: 2ndgoods

services:
  mysql_db:
    container_name: 2ndgoods_db
    image: mysql:5.7
    restart: always
    volumes:
      - $HOME/database:/var/lib/mysql
    env_file: ./.env.deploy
    environment:
      <<: *common-variables
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: 300618
    ports:
      - 3306:3306
    # expose:
    #   - 3307
    networks:
      - twohands

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql_db
    links:
      - mysql_db:mysql_db
    ports:
      - 8080:80
    restart: always

  app_be:
    container_name: 2ndgoods_be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # env_file: ./.env.deploy
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    links:
      - mysql_db
    command:
      - sh
      - -c
      - 'npm run init-database && npm start'
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - twohands
    depends_on:
      - mysql_db
networks:
  twohands:
    driver: bridge